name: Test build wheels

on:
  workflow_dispatch:

jobs:
  # build_linux_wheels:
  #   name: Build wheels on standard linux
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: recursive
  #         fetch-depth: 2

  #     - name: Build wheels
  #       uses: pypa/cibuildwheel@v2.13.1
  #       env:
  #         CIBW_BUILD: "*manylinux*"
  #         CIBW_SKIP: cp36* cp37* pp*
  #         CIBW_BUILD_VERBOSITY: 3
  #         CIBW_BEFORE_BUILD: pip install -U pybind11-global
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         path: ./wheelhouse/*.whl

  # build_musl_wheels:
  #   name: Build wheels on musl linux
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: recursive
  #         fetch-depth: 2

  #     - name: Build wheels
  #       uses: pypa/cibuildwheel@v2.13.1
  #       env:
  #         CIBW_BUILD: "*musllinux*"
  #         CIBW_SKIP: cp36* cp37* pp*
  #         CIBW_BUILD_VERBOSITY: 3
  #         CIBW_BEFORE_BUILD: pip install -U pybind11-global
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         path: ./wheelhouse/*.whl

  build_macosx_wheels:
    name: Build wheels on macosx
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Tinkering with https://github.com/actions/runner-images/issues/5555
      # to get OpenMP working on MacOS
      # Currently I get
      #   OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
      #   OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. ...
      - name: Compile a universal OpenMP
        run: brew reinstall -v --build-from-source --formula ./recipe/libomp.rb

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.1
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_BUILD: "cp310*arm*"
          CIBW_SKIP: cp36* cp37* pp*
          CIBW_BUILD_VERBOSITY: 3
          CIBW_BEFORE_BUILD: pip install -U pybind11-global
          # CIBW_BEFORE_TEST: pip install -U -r test_requirements.txt
          # CIBW_TEST_COMMAND: pytest --skip_gha {package}/tests
          # CIBW_TEST_SKIP: "*_arm64 *_universal2:arm64"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
